# ------------------------------------------------------------------------
#  RAVYNOS BUILD SYSTEM - Frameworks
# ------------------------------------------------------------------------

SUBDIR += CoreFoundation
#SUBDIR += CFNetwork
SUBDIR += Foundation
SUBDIR += CoreServices
SUBDIR += UIKit

.include <bsd.subdir.mk>
