PACKAGE_NAME = libs-uikit

include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = libs-uikit

libs-uikit_OBJC_FILES = \
	UIResponder.m \
	UIApplication.m \
	UIView.m \
	UIWindow.m \
	UIViewController.m \
	UIColor.m \
	UIImage.m \
	UIFont.m \
	UILabel.m \
	UIImageView.m \
	UIControl.m \
	UIButton.m \
	UITextField.m \
	UITextView.m \
	UISlider.m \
	UISwitch.m \
	UISegmentedControl.m \
	UIScrollView.m \
	UITableViewCell.m \
	NSIndexPath+UIKit.m \
	UITableView.m \
	UIOpenGLView.m \
	UINavigationItem.m \
	UINavigationController.m \
	UITabBarController.m \
	UIActivityIndicatorView.m \
	UIAlertView.m \
	UIScreen.m \
	UIDevice.m \
	UINib.m \
	NSBundle+UIKit.m

libs-uikit_HEADER_FILES_DIR = ../Headers/UIKit
libs-uikit_HEADER_FILES_INSTALL_DIR = /UIKit
libs-uikit_HEADER_FILES = \
	UIKit.h \
	UIKitTypes.h \
	UIResponder.h \
	UIApplication.h \
	UIView.h \
	UIWindow.h \
	UIViewController.h \
	UIColor.h \
	UIImage.h \
	UIFont.h \
	UILabel.h \
	UIImageView.h \
	UIControl.h \
	UIButton.h \
	UITextField.h \
	UITextView.h \
	UISlider.h \
	UISwitch.h \
	UISegmentedControl.h \
	UIScrollView.h \
	UITableViewCell.h \
	NSIndexPath+UIKit.h \
	UITableView.h \
	UIOpenGLView.h \
	UINavigationItem.h \
	UINavigationController.h \
	UITabBarController.h \
	UIActivityIndicatorView.h \
	UIAlertView.h \
	UIScreen.h \
	UIDevice.h \
	UINib.h \
	NSBundle+UIKit.h

libs-uikit_LIBRARIES_DEPEND_UPON = -lgnustep-gui -lgnustep-base

include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
include GNUmakefile.postamble
