include $(GNUSTEP_MAKEFILES)/common.make

FRAMEWORK_NAME = UIKit
UIKit_FRAMEWORK_DIR = .

UIKit_OBJC_FILES = \
    UIResponder.m \
    UIView.m \
    UIWindow.m \
    UIApplication.m \
    UIViewController.m \
    UIScreen.m \
    UIDevice.m \
    UIEvent.m \
    UIColor.m \
    UIFont.m \
    UIImage.m \
    UIImageView.m \
    UILabel.m \
    UIButton.m \
    UIGestureRecognizer.m \
    UITableView.m \
    UITableViewCell.m \
    UIStackView.m \
    UIAccessibility.m

UIKit_HEADER_FILES = \
    UIKit.h \
    UIKitExport.h \
    UIGeometry.h \
    UIResponder.h \
    UIView.h \
    UIWindow.h \
    UIApplication.h \
    UIViewController.h \
    UIScreen.h \
    UIDevice.h \
    UIEvent.h \
    UIColor.h \
    UIFont.h \
    UIImage.h \
    UIImageView.h \
    UILabel.h \
    UIButton.h \
    UIGestureRecognizer.h \
    UITableView.h \
    UITableViewCell.h \
    UIStackView.h \
    UIAccessibility.h

UIKit_RESOURCE_FILES = \
    Info.plist

ADDITIONAL_OBJCFLAGS = -fexceptions -fobjc-exceptions -I.. -I../CoreFoundation -I../CoreGraphics

include $(GNUSTEP_MAKEFILES)/framework.make
