include "$(GNUSTEP_MAKEFILES)/common.make"

KEXT_NAME = QualcommMMC
QualcommMMC_OBJC_FILES = \
	QualcommMMC.mm \
	QualcommMMCFileSystems.mm \
	QualcommMMCFileSystemExt3.mm \
	QualcommMMCFileSystemFAT.mm \

QualcommMMC_OUT_NSBundle := QualcommMMC.kext

include "$(GNUKEXT_MAKEFILES)/kext.make"