include $(GNUSTEP_MAKEFILES)/common.make

# GUI Application
APP_NAME = InstallPocketDarwin
$(APP_NAME)_OBJC_FILES = Setup.m
$(APP_NAME)_RESOURCE_FILES =
$(APP_NAME)_FRAMEWORKS = AppKit Foundation
$(APP_NAME)_INSTALL_PATH = /Applications
include $(GNUSTEP_MAKEFILES)/application.make
